services:
  backend:
    build: ./backend
    container_name: ai-rag-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/uploads:/app/uploads
      - hf_cache:/root/.cache/huggingface
    restart: always
    labels:
      - "coolify.managed=true"
      - "coolify.fqdn=https://api-ai-rag.md-x.dev"
      - "coolify.port=8000"

  frontend:
    build: ./frontend
    container_name: ai-rag-frontend
    environment:
      - NEXT_PUBLIC_API_URL=https://api-ai-rag.md-x.dev
    depends_on:
      - backend
    restart: always
    labels:
      - "coolify.managed=true"
      - "coolify.fqdn=https://ai-rag.md-x.dev"
      - "coolify.port=3000"

volumes:
  hf_cache:
